[package]
name = "psi_insar_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "= 0.4.39", features = ["serde"] }
geo-types = "0.7.16"
geotiff = { path = "../geotiff", features = ["tie-points"] }
nalgebra = "0.33.2"
ndarray = "0.16.1"
num-complex = "0.4.6"
quick-xml = { version = "0.37.2", features = ["serde", "serialize"] }
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
serde_path_to_error = "0.1.17"
thiserror = "2.0.11"

[dev-dependencies]
# gltf = "1.4.1"
rerun = { version = "0.22.1", default-features = false, features = ["sdk"] }
